sudo: required
dist: trusty
services:
  - docker
env:
  global:
    secure: "l5Ko1ZgDCafxDFVCWxRx2nLTiXXxUHcvC2sBZqVg/A5QBob2aQzcc7dFoxw/pb42G+qZnqlz3m2AYrq8Y+iJ2R//ZMzlHcTYI2jd7gXZIC41I1QFPhtwPHfixlTthMoG43Qg9t1h9jxNQu2QFit0Nj0t3EllHIaELoKfAE73HcRH6mHtXnbKJRNNhG1/Bg39bVonJycFn2CpIlmFKHOliurwUIFnhRkTsSJ4X7y2SLYWASEceFeFsKG1M52k7qfJcPIK5aq9hi53HPInUfksgBJTsU7rupqQr0C1rnkyFZKSrg+TFqF1KyLqJNN475FkpwYf0g1q0uNQYVbgJeP0BaElwsafPPFb0rrpPtXr7h2+b6HwAzo0/bRqHCNsw3P4RBsq44iX4MsoKhlxbADd4ZgIfRCo0pkSEq+x3LsBBf9blikLuCc2SC16C4NQ797bQ8bPwm2Z8teP/SlrU0B8AhZ4lXYeKL366RMUshgHWi+Pjcg+1sA6M01g6lHjqLHqaTLAXFq4ykzJWEbBdpiFncZpN35DLslhCqszJfmFHNfrkDU5uvrS6rt/ryx0R1Du3tkw2IneS1eEgCUUdlcB53Jn+OR2ZedhXgtsOfncti+7b1BgP0Z9j3tn06t92bb1xBtDmKOaloHNewmN3rck9Zy5YD/4mMFNvJU0mE3lD58="
    secure: "G2ULsvmi4pMQUIXK0gjFaIN6AeAppmCdVz9KwaudExMRw5f0RiFveC13wYc5+bsqhhWykekgQk8wmTkNhDIeYoCtVyWRg1tP4mO2iiqXP6tnY3ZOvLgtF3LgO3v9WRTt9jKdrbLi27lGXnZ2xNogLxE2s1ms5cfUuoEGatVTljDdMT6KrcaX2duCZUayx2hTRlMuE4ZHhbKGfQfZ/+uWbKCiZ90G+BUbdJ1AMcg5K1bcwXdv3qZvOazUWt6miS+V81jYsoEP4Xayt+ChCN5zTfYHgjw9G4CDC96qug4Y/7asYYttdpDtea6cI3+IeYw3I3ng9EX4UlgEbGTlU2OT1GzMdBwXk/LoOPzBEQA+UeR8cEX/dC0X72y7AMEt/BsWsRRJHOM9f8GmxObLctgyHwAXXvUzHUMZcJfKrvaRfVZ6qn82W2BFymOMhCyy5Xp3ivA7/84cyy/GloOP5zS3VRQj7CpaesQJ0IisdXWx78mw0O0tl2E2aCXUboaEWNnMP27jdfZCdgryrgMKi5khOmemqLOOrAeO62R0VvOMGGJgl/BkhBqJLXnuSz8TPmpxAFpBNk1adNQpOP5ZV302jBkytrdmiQGVCtKYNAomlnW8Vt/mZ+OsCcTG1Ylfebfoyjs8+aAtsG7hXidCYR1UlrHLHW8mrOXTpe/f4mX8NU8="

install:
  - rvm install 2.3
script:
  - ./.travis-test.sh

# Upload packages on successful tagged builds:
deploy:
  provider: script
  script: "make upload-packages"
  skip_cleanup: true
  on:
    tags: true
